#' Generate data frame with estimation data to ease the plotting process
#'
#' The function generates a data frame based on estimation tabulates.
#'
#' @description
#' This function generates a data frame with estimation data which should substantially ease the plotting process.
#'
#' @param mydata Data frame containing complete information on all estimations.
#' @param id_estimacion_vec Specific ID used to identify estimations. Consists of a character
#'        vector. Default value is \code{"prop_cuid_inact"}.
#' @param nudge_x Numeric vector indicating how much distance should be plotted between
#'        the upper confidence interval and the visualization of the point estimate (Note:
#'        this argument is relevant only for lollipop plots and has no bearing on plotting barplots).
#'        Default value is \code{0.08}.
#' @param nudge_y Numeric vector indicating how much distance should be plotted between the
#'        lower confidence interval and the visualization of the point estimate (Note:
#'        this argument is relevant only for barplots and has no bearing on plotting lollipop plots).
#'        Default value is \code{0.05}.
#' @param str_wrap Numeric vector indicating how many characters should a string possess before
#'        automatically inserting a new paragraph. Useful for plots where categories have long
#'        labels.
#'
#' @details
#' The function operates in the following way:
#' \itemize{
#'   \item The function filters the original data frame for a specific \code{id_estimacion},
#'         so that only information on a specific estimation is preserved.
#'   \item The function extracts select specific columns necessary for plotting.
#'   \item Afterwards, generates two new columns: \code{nudge_x_upp} by adding \code{upp} and
#'         \code{nudge_x}, and \code{nudge_y_low} by adding \code{low} and \code{nudge_y}.
#'   \item The function then applies str_wrap con the val_label column.
#'   \item Finally, the function consolidates two specific columns containing labels
#'         from character type to factor type.
#' }
#'
#' @return
#' A data frame containing tabular data for socio-demographic and time-use estimations.
#'
#' @importFrom sjlabelled to_factor
#' @importFrom forcats fct_reorder
#' @importFrom stringr str_wrap
#' @export
cargar_obj_tab <-
  function(
    mydata,
    id_estimacion_vec = "prop_cuid_inact",
    nudge_x = 0.08,
    nudge_y = 0.05,
    str_wrap = 12
  ) {
    ### 1. Abrir ambiente de función ###########################################

    ### 2. Crear data frame filtrado ###########################################
    df_est_short <-
      mydata %>%
      filter(id_estimacion %in% id_estimacion_vec)

    ### 3. Seleccionar y transformar columnas de interés #######################
    df_est_short <-
      df_est_short %>%
      select(
        titulo,
        id_estimacion,
        id_obj_agg,
        variable,
        variable_label,
        val,
        val_label,
        group_var,
        group_var_label,
        cats_group_var,
        cats_group_var_label,
        estimate,
        estimate_format_asterisk,
        low,
        upp
      ) %>%
      mutate(
        val = as.numeric(val),
        cats_group_var = as.numeric(cats_group_var)
      ) %>%
      arrange(
        id_estimacion,
        val,
        cats_group_var
      )

    ### 4. Crear col. de distancia entre intervalos y est. puntual #############
    df_est_short <-
      df_est_short %>%
      rowwise() %>%
      mutate(
        nudge_x_upp = sum(upp, nudge_x, na.rm = TRUE)
      ) %>%
      ungroup()

    df_est_short <-
      df_est_short %>%
      rowwise() %>%
      mutate(
        nudge_y_low = sum(low, -1 * nudge_y, na.rm = TRUE)
      ) %>%
      ungroup()

    ### 5. Aplicar str_wrap a val_label ########################################
    df_est_short <-
      df_est_short %>%
      mutate(val_label = stringr::str_wrap(val_label,
        width = str_wrap
      ))

    ### 6. Convertir columnas de etiquetas (chr) a factores ####################
    df_est_short <-
      df_est_short %>%
      mutate(
        cats_group_var_label = forcats::fct_reorder(.f = cats_group_var_label, .x = cats_group_var),
        val_label = forcats::fct_reorder(.f = val_label, .x = val)
      ) %>%
      mutate(
        val_label = forcats::fct_rev(val_label) # invertir orden de factores para efectos de plottear
      )

    ### 7. Señalar objeto a entregar ###########################################
    return(df_est_short)

    ### 8. Cerrar ambiente de función ##########################################
  }

#' Plot customized ggplot2 bar plots
#'
#' This function was designed to enable the user to easily generate
#' ggplot2 barplots based on tidy tabular data generated by
#' \code{\link[enuttools]{cargar_obj_tab}} with minimal code input.
#' However, the function is
#' flexible enough so that the user can plot customized bar plots
#' based on tidy tabular data generated by other means, not using
#' \code{\link[enuttools]{cargar_obj_tab}} (the expected workflow).
#'
#' @description
#' This function is intended to allow the generation of bar plots
#' with little code input as part of a workflow where tidy tabular
#' data is generated using \code{\link[enuttools]{cargar_obj_tab}}. If
#' using the expected workflow, the user does not need to specify too
#' many parameters, so that plots can be built with little code input.
#' 
#' @param mydata A data frame containing tidy data based on survey value estimations.
#' @param cats_group_var A vector inside the data frame denoting a grouping
#'        variable and its categories. Default value is \code{"cats_group_var_label"}.
#' @param media A vector inside the data frame denoting where the function
#'        must look for the tabulated values. In the case of the present
#'        function, the expected value is a mean. Therefore, the default
#'        value for this parameter is \code{"estimate"}.
#' @param media_label A vector inside the data frame denoting where the function
#'        must look for labelled values. In the case of the present function, the
#'        expected value is a labelled mean (e.g., "2,05" instead of "2.04922222").
#'        The default value for this parameter is \code{"estimate_format_asterisk"}. The asterisk
#'        denotes whether the estimation is reliable, weakly reliable or not reliable.
#' @param media_low A vector inside the data frame denoting where the function must
#'        look for the lower tail for confidence intervals. Default value is \code{low}.
#' @param media_upp A vector inside the data frame denoting where the function must
#'        look for the upper tail for confidence intervals. Default value is \code{upp}.
#' @param bar_width Numeric vector (ranging from 0 to 1) denoting bar
#'        width. Default value is \code{0.4}.
#' @param ci_color Character vector denoting the color the confidence
#'        intervals must have. Default value is \code{"black"}.
#' @param lab_x Label for the x-axis variable. Default value is \code{NULL}.
#' @param lab_y Label for the y-axis variable. Default value is \code{"Tiempo (horas)"},
#'        which is only suitable for time-use estimations.
#' @param bar_colors Character vector denoting the color or colors for
#'        either both or each bar. Default colors are \code{"#ccebhc5"} and \code{"#decbe4"}.
#' @param nudge_y_low Name of the column where the value for the distance between
#'        point estimate display and lower confidence interval tail can be found.
#'        Default value is \code{"nudge_y_low"}.
#'
#' @details
#' The function operates in the following way:
#' \itemize{
#'   \item The function first generates a simple ggplot2 plot by
#'         specifying ggplot2 basics: data, mapping (x, y and fill),
#'         and then adding a \code{geom_bar()}.
#'   \item The function then adds an error bar to allow graphical
#'         display of confidence intervals. Note that confidence
#'         interval values must be already calculated and contained
#'         as columns inside your tidy tabular data frame.
#'   \item The function then adds the themes for the plot.
#'   \item The function then adds captions for the plot.
#'   \item The function then formats the appearance of the y-axis
#'         (composed of continuous values). The x-axis does not require
#'         specific formatting because its values are expected to form an ordered factor in the
#'         tidy data frame.
#'   \item Finally, the function specifies manual color categories
#'         for the bar colors.
#' }
#'
#' @return A ggplot2 customized bar plot.
#'
#' @seealso \code{\link[ggplot2]{ggplot}},
#' \code{\link[enuttools]{cargar_obj_tab}}.
#'
#' @import ggplot2
#'
#' @export

cplot_barplot <-
  function(mydata,
           cats_group_var = "cats_group_var_label",
           media = "estimate",
           media_label = "estimate_format_asterisk",
           media_low = "low",
           media_upp = "upp",
           bar_width = 0.4,
           ci_color = "black",
           lab_x = NULL,
           lab_y = "Tiempo (horas)",
           bar_colors = c("#ccebc5", "#decbe4"),
           nudge_y_low = "nudge_y_low") {
    ### 1. Abrir ambiente de función ###########################################

    ### 2. Crear objetos auxiliares ############################################
    ci_width <- bar_width / 2

    ### 3. Crear barplot básico ################################################
    mybarplot <-
      ggplot2::ggplot(
        data = mydata,
        mapping =
          aes(
            x = !!rlang::parse_expr(cats_group_var),
            y = !!rlang::parse_expr(media),
            fill = !!rlang::parse_expr(cats_group_var)
          )
      ) +
      ggplot2::geom_bar(
        stat = "identity",
        position = "dodge",
        width = bar_width
      )

    ### 4. Agregar intervalos de confianza #####################################
    mybarplot <-
      mybarplot +
      ggplot2::geom_errorbar(
        mapping = aes(
          ymin = !!rlang::parse_expr(media_low),
          ymax = !!rlang::parse_expr(media_upp)
        ),
        color = ci_color,
        width = ci_width
      )

    ### 5. Agregar tema ########################################################
    mybarplot <-
      mybarplot +
      ggplot2::theme_minimal() +
      ggplot2::theme(legend.position = "none")

    ### 6. Agregar captions ####################################################
    mybarplot <-
      mybarplot +
      ggplot2::labs(
        x = lab_x,
        y = lab_y
      )

    mybarplot <-
      mybarplot +
      ggplot2::geom_text(
        data = mydata,
        mapping = aes(
          y = !!rlang::parse_expr(nudge_y_low),
          label = !!rlang::parse_expr(media_label)
        )
      )

    ### 7. Eje Y ###############################################################
    mybarplot <-
      mybarplot +
      ggplot2::scale_y_continuous(
        labels = scales::number_format(big.mark = ".", decimal.mark = ",")
      )

    ### 8. Especificar colores de las barras ###################################
    mybarplot <-
      mybarplot +
      ggplot2::scale_fill_manual(
        values = bar_colors
      )

    ### 9. Señalar objeto a devolver ###########################################
    return(mybarplot)

    ### 10. Cerrar ambiente de función #########################################
  }

#' Plot customized ggplot2 lollipop plots
#'
#' This function was designed to enable the user to easily generate
#' ggplot2 lollipop plots based on tidy tabular data generated by
#' \code{\link[enuttools]{cargar_obj_tab}} and further processing if necessary.
#'
#' @description
#' This function is intended to allow the generation of lollipop plots
#' with variable code input as part of a workflow where tidy tabular
#' data is generated using \code{\link[enuttools]{cargar_obj_tab}} along with further
#' data wrangling and processing if necessary. If the user follows the expected workflow,
#' there should be no need to specify too
#' many parameters, so that plots themselves can be built with little code input.
#' But be aware that generating tidy tabular data frames can require a certain amount
#' of code input.
#'
#' @param mydata Tidy tabular data frame or tibble.
#' @param prop Name of the column where the point estimate for a proportion is
#'        stored. Default value is \code{"estimate"}.
#' @param cats_group_var_label A vector inside the data frame denoting the (labelled)
#'        values of a grouping variable. Default value is \code{"cats_group_var_label"}.
#' @param prop_label Name of the column where the point estimate for a proportion
#'        is stored in a formatted string (e.g., a string such as \code{"25,2\%"} instead
#'        of \code{"0.252112"}). Default value is \code{"estimate_format_asterisk"}.
#' @param prop_low Name of the column where the value for the lower tail of
#'        the confidence interval for a proportion can be found. Default value
#'        is \code{"low"}.
#' @param prop_upp Name of the column where the value for the upper tail of
#'        the confidence interval for a proportion can be found. Default value
#'        is \code{"upp"}.
#' @param lab_y String for the y-axis label. Default value is NULL.
#' @param lab_x String for the x-axis label. Default value is \code{"Población que
#'        participa (\%)"}
#' @param nudge_x_upp Name of the column where the value for the distance between
#'        point estimate display and upper confidence interval tail can be found.
#'        Default value is \code{"nudge_x_upp"}.
#' @param expand Value of \code{expand} inside \code{\link[ggplot2]{scale_x_continuous}}.
#'        Default value is \code{c(0,0.2)}.
#' @param limits Value of \code{limits} inside \code{\link[ggplot2]{scale_x_continuous}}.
#'        Default value is \code{c(0,1)}.
#'
#' @details
#' The function operates in the following way:
#' \itemize{
#'   \item The function first generates a basic mapping using the aesthetics
#'         \code{x = grouping} variable and \code{y = value} for the proportion, after which it
#'         adds two separate elements to the plot: a
#'         geom_segment line and a geom_point so as to build the "lollipop"
#'         plot image.
#'   \item The function then adds error bars around the point estimation
#'         based on values for both tails of the confidence intervals found
#'         on the data frame.
#'   \item The function then adds a text label for the point-estimation value
#'         located to the right of the upper confidence interval bar.
#'   \item The function then customizes the x-axis (x-axis is customized as
#'         as continuous using \code{\link[scales]{label_percent}}).
#'   \item The function afterwards specifies labels and themes for the plot.
#' }
#'
#' @return A ggplot2 customized lollipop plot.
#' @seealso \code{\link[ggplot2]{ggplot}},
#' \code{\link[enuttools]{cargar_obj_tab}}.
#'
#' @import ggplot2
#'
#' @export

cplot_lollipop <-
  function(
    mydata,
    prop = "estimate",
    cats_group_var_label = "cats_group_var_label",
    prop_label = "estimate_format_asterisk",
    prop_low = "low",
    prop_upp = "upp",
    lab_y = NULL,
    lab_x = "Poblaci\u00f3n que participa (\u0025)",
    nudge_x_upp = "nudge_x_upp",
    expand = c(0, 0.02),
    limits = c(0, 1)
  ) {
    ### 1. Abrir ambiente de función ###########################################

    ### 2. Crear plot básico ###################################################
    ### Las líneas y el círculo deben graficarse por separado
    myplot <-
      ggplot2::ggplot(
        data = mydata,
        mapping = aes(
          x = !!rlang::parse_expr(prop),
          y = !!rlang::parse_expr(cats_group_var_label),
          label = !!rlang::parse_expr(prop_label)
        )
      ) +
      ### Líneas
      ggplot2::geom_segment(
        mapping = aes(
          x = 0,
          y = !!rlang::parse_expr(cats_group_var_label),
          xend = !!rlang::parse_expr(prop),
          yend = !!rlang::parse_expr(cats_group_var_label)
        ),
        color = "grey50"
      ) +
      ### Intervalos de confianza
      ggplot2::geom_errorbar(
        data = mydata,
        mapping = aes(
          xmin = !!rlang::parse_expr(prop_low),
          xmax = !!rlang::parse_expr(prop_upp)
        ),
        width = 0.3
      ) +
      ### Círculo
      ggplot2::geom_point(
        size = 1,
        color = "#BC658D",
        fill = "#BC658D",
        alpha = 1,
        shape = 21,
        stroke = 1
      )

    ### 3. Agregar texto de estimación puntual #################################
    myplot <-
      myplot +
      ggplot2::geom_text(
        mapping = aes(
          x = !!rlang::parse_expr(nudge_x_upp)
        ),
        size = 3
      )

    ### 4. Modificar escala del eje X ##########################################
    myplot <-
      myplot +
      ggplot2::scale_x_continuous(
        labels = scales::label_percent(big.mark = ".", decimal.mark = ","),
        expand = expand,
        limits = limits,
        breaks = c(0, 0.25, 0.5, 0.75, 1)
      )

    ### 5. Agregar etiquetas ###################################################
    myplot <-
      myplot +
      ggplot2::labs(
        y = lab_y,
        x = lab_x
      )

    ### 6. Modificar tema ######################################################
    myplot <-
      myplot +
      ggplot2::theme_bw() +
      ggplot2::theme(axis.ticks.y = element_blank())

    ### 7. Señalar objeto a devolver ###########################################
    return(myplot)

    ### 8. Cerrar ambiente de función ##########################################
  }

#' Facet-wrap customized ggplot2 lollipop plots
#'
#' This function was designed to enable the user to easily generate
#' ggplot2 lollipop plots for several groups building upon the
#' \code{\link[enuttools]{cplot_lollipop}} function. Multiple plots are generated
#' by using \code{\link[ggplot2]{facet_wrap}}.
#'
#' @description
#' This function is intended to allow the generation of lollipop plots for multiple plots
#' with variable code input as part of a workflow where tidy tabular
#' data is generated using \code{\link[enuttools]{cargar_obj_tab}} and the basic structure
#' for lollipop plots is generated using \code{\link[enuttools]{cplot_lollipop}}.
#' If the user follows the expected workflow, there should be no need to specify too
#' many parameters, so that plots themselves can be built with little code input.
#'
#' @param mydata Tidy tabular data frame or tibble.
#' @param prop Name of the column where the point estimate for a proportion is
#'        stored. Default value is \code{"estimate"}.
#' @param cats_group_var_label A vector inside the data frame denoting the (labelled)
#'        values of a grouping variable. Default value is \code{"cats_group_var_label"}.
#' @param prop_label Name of the column where the point estimate for a proportion
#'        is stored in a formatted string (e.g., a string such as \code{"25,2\%"} instead
#'        of \code{"0.252112"}). Default value is \code{"estimate_format_asterisk"}.
#' @param prop_low Name of the column where the value for the lower tail of
#'        the confidence interval for a proportion can be found. Default value
#'        is \code{"low"}.
#' @param prop_upp Name of the column where the value for the upper tail of
#'        the confidence interval for a proportion can be found. Default value
#'        is \code{"upp"}.
#' @param lab_y String for the y-axis label. Default value is \code{NULL}.
#' @param lab_x String for the x-axis label. Default value is \code{"Población que
#'        participa (\%)"}.
#' @param variable Name of the column where the variable name is stored. \code{variable}
#'        becomes a part of the formula necessary to perform \code{\link[ggplot2]{facet_wrap}}.
#'        Default value is \code{"variable"}.
#' @param nudge_x_upp Name of the column where the value for the distance between
#'        point estimate display and upper confidence interval tail can be found.
#'        Default value is "nudge_x_upp".
#' @param expand Value of \code{expand} inside \code{\link[ggplot2]{scale_x_continuous}}.
#'        Default value is \code{c(0,0.2)}.
#' @param ncol Value of \code{ncol} inside \code{\link[ggplot2]{facet_wrap}}. Default
#'        value is 1.
#' @param nrow Value of \code{nrow} inside \code{\link[ggplot2]{facet_wrap}}. Default
#'        value is 4.
#' @param limits Value of \code{limits} inside \code{\link[ggplot2]{scale_x_continuous}}.
#'        Default value is \code{c(0,1)}.
#'
#' @details
#' The function operates in the following way:
#' \itemize{
#'   \item The function first generates a basic lollipop plot using \code{\link[enuttools]{cplot_lollipop}}.
#'   \item The function then facet-wraps the plot based on the values provided by
#'         \code{variable}.
#' }
#'
#' @return A ggplot2 customized lollipop plot.
#'
#' @seealso \code{\link[ggplot2]{ggplot}},
#'          \code{\link[enuttools]{cargar_obj_tab}},
#'          \code{\link[enuttools]{cplot_lollipop}}.
#'
#' @importFrom ggplot2 facet_wrap
#' @importFrom stats as.formula
#'
#' @export

cplot_lollipop_fw <-
  function(
    mydata,
    prop = "estimate",
    cats_group_var_label = "cats_group_var_label",
    prop_label = "estimate_format_asterisk",
    prop_low = "low",
    prop_upp = "upp",
    lab_y = NULL,
    lab_x = "Poblaci\u00f3n que participa (\u0025)",
    variable = "variable",
    nudge_x_upp = "nudge_x_upp",
    expand = c(0, 0.02),
    ncol = 1,
    nrow = 4,
    limits = c(0, 1)
  ) {
    ### 1. Abrir ambiente de función ###########################################

    ### 2. Crear plot básico ###################################################
    myplot <-
      enuttools::cplot_lollipop(
        mydata = mydata,
        prop = prop,
        cats_group_var_label = cats_group_var_label,
        prop_label = prop_label,
        prop_low = prop_low,
        prop_upp = prop_upp,
        lab_y = lab_y,
        lab_x = lab_x,
        nudge_x_upp = nudge_x_upp,
        expand = expand,
        limits = limits
      )

    ### 3. Agregar facet_wrap ##################################################
    myplot <-
      myplot +
      ggplot2::facet_wrap(as.formula(paste0("~", variable)),
        ncol = ncol,
        nrow = nrow
      )

    ### 4. Señalar objeto a devolver ###########################################
    return(myplot)

    ### 5. Cerrar ambiente de función ##########################################
  }
