utils::globalVariables(c(
  ".", ".I", ".SD", "col3", "expr", "id", "val_error",
  "value", "var", "var_mod", "var_qst", "var_val"
))

utils::globalVariables(c(
  "id_per",
  "informante_kish",
  "insuf_ch_hog",
  "insuf_ch_per",
  "interview__key",
  "modulo",
  "n_habilitadas",
  "n_sets_respondidos",
  "n_validas",
  "pct_esen_cut",
  "pct_valid_cut",
  "pct_validas",
  "respondido",
  "set",
  "set_respondido",
  "total_horas",
  "valor",
  "valor_numerico",
  "variable"
))

utils::globalVariables(c(
  "actividad",
  "analisis_insumo",
  "aux", "aux2", "aux3", "aux4",
  "c1", "c5",
  "cats_group_var", "cats_group_var_label",
  "cd1", "cd1_papel", "cd2", "cd2_papel",
  "design_ch", "design_cut",
  "edad_min",
  "est_var_factor",
  "estimate", "estimate_format_asterisk",
  "folio",
  "group.var", "group_var", "group_var_label",
  "h1", "hay_subpop",
  "hdr_cut_fecha_visita",
  "hhmm", "hhmm_abs",
  "hrs",
  "id_cuid", "id_estimacion", "id_obj_agg",
  "label", "level",
  "low", "upp",
  "marca_subpop",
  "mins",
  "mm", "mm_abs",
  "n_linea_p",
  "n_preg_tiempo_respondidas",
  "name",
  "ot1a_1", "ot1a_2", "ot1a_3", "ot1a_4",
  "ot1a_5", "ot1a_6", "ot1a_7", "ot1a_8",
  "padre_hogar_count",
  "participa",
  "pct_obs",
  "persona_linea",
  "pmrural", "pmrural_val",
  "recolec_sm1", "recolec_sm2",
  "regla",
  "riesgo_global_chr", "riesgo_jerarq_chr",
  "rph3", "rph4",
  "sign_t",
  "sm",
  "suegro_hogar_count",
  "sujetos_cuidado_4_o_psdf",
  "sujetos_cuidado_14_o_psdf",
  "sujetos_cuidado_psdf",
  "tc", "tc5_p_ds", "tc6_p_ds",
  "tiempo", "time",
  "titulo",
  "val", "val_label",
  "valprimer_insumo", "valseg_insumo",
  "var_rename",
  "variable_label",
  "col2", "act_regla"
))
